### ISSUE TITLE
Integration for Swift

### ISSUE THREAD

**Issue by kunalgupta1593** [hanselio/hansel.io-ios#1]
Hi there , I am trying to integrate Hansel SDK in my Swift App. Can you please help me with the extra steps that i need to perform for integration in swift . I just mean the name of the file that i need to import in my Bridging Header. I am trying to add this SDK for iOS 10.

**Comment by muditkmathur** [comment]
Hi Kunal, 

Thanks for your interest in hansel.io. We are under private beta for Obj-C and are currently working with a selected group of companies. Please do mail me at mudit@hansel.io or hi@hansel.io if you would like to be part of our beta test group. 

We are still working on our Swift solution and are not ready with it yet. I would notify you once we are ready with it.

-Mudit

**Comment by kunalgupta1593** [comment]
Thanks a lot Mudit for your time and support.
